- schemaLabel: some example schema
  schemaURL: example.shex
  dataLabel: and example data
  dataURL: example.ttl
  queryMap: |-
    lovd:variants\/0000001345\#00000064@<#VariantOnTranscription>,
    lovd:variants\/0000001344\#00000064@<#VariantOnTranscription>,
    lovd:variants\/0000001345\#vog@<#VariantOnGenome>,
    lovd:variants\/0000001344\#vog@<#VariantOnGenome>,
    lovd:variants\/0000001345@<#GeneticMeasurementOutput>,
    lovd:variants\/0000001344@<#GeneticMeasurementOutput>,
    lovd:screenings\/0000000117\#genotype@<#GenotypeAttribute>,
    lovd:screenings\/0000000117@<#GeneticMeasurementProcess>,
    lovd:individuals\/00000125\#diagnosis@<#DiagnosisAttribute>,
    lovd:individuals\/00000125\#findings@<#DiagnosisMeasurementOutput>,
    lovd:individuals\/00000125\#examination@<#DiagnosisMeasurementProcess>,
    lovd:individuals\/00000125\#role@<#PatientRoleShape>,
    lovd:individuals\/00000125@<#PersonShape>,
    lovd:individuals\/00000125\#identifier@<#PatientIdentifierShape>,
  status: conformant
