- schemaLabel: EJP-RD-LOVD model
  schemaURL: schemas/v.1.0/LOVD.shex
  dataLabel: EJP-RD-LOVD example data
  dataURL: examples/LOVD.ttl
  queryMap: |-
    lovd:variants\/0000001345\#00000064@<#VariantOnTranscription>,
    lovd:variants\/0000001344\#00000064@<#VariantOnTranscription>,
    lovd:variants\/0000001345\#vog@<#VariantOnGenome>,
    lovd:variants\/0000001344\#vog@<#VariantOnGenome>,
    lovd:variants\/0000001345@<#GeneticMeasurementOutput>,
    lovd:variants\/0000001344@<#GeneticMeasurementOutput>,
    lovd:screenings\/0000000117\#genotype@<#GenotypeAttribute>,
    lovd:screenings\/0000000117@<#GeneticMeasurementProcess>,
    lovd:individuals\/00000125\#diagnosis@<#DiagnosisAttribute>,
    lovd:individuals\/00000125\#findings@<#DiagnosisMeasurementOutput>,
    lovd:individuals\/00000125\#examination@<#DiagnosisMeasurementProcess>,
    lovd:individuals\/00000125\#role@<#PatientRoleShape>,
    lovd:individuals\/00000125@<#PersonShape>,
    lovd:individuals\/00000125\#identifier@<#PatientIdentifierShape>,
  status: conformant
